// Code generated by tools/genui from ui.spec.json. DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 the Mosaic authors

import { ActionKind, type Action } from "./contract.gen.js";
import { compose, Prop, Slot, type El, type Elish, type Element, type Props } from "./ui_runtime.js";

export { Group, ID, Prop, Slot, When, Element } from "./ui_runtime.js";
export type { El, Elish, Props } from "./ui_runtime.js";
export { ActionKind, Surface, Tone } from "./contract.gen.js";
export type { Action, UINode } from "./contract.gen.js";

// ── components ─────────────────────────────────────────────────────────────

/** Screen is the root of a server-defined page. */
export function Screen(...els: Elish[]): Element {
  return compose("Screen", undefined, els);
}

/** Section is a titled band. */
export function Section(title: string, ...els: Elish[]): Element {
  return compose("Section", { title }, els);
}

/** Carousel is a horizontal snap-scrolling rail. */
export function Carousel(...els: Elish[]): Element {
  return compose("Carousel", undefined, els);
}

/** Grid is a responsive auto-fill grid. */
export function Grid(...els: Elish[]): Element {
  return compose("Grid", undefined, els);
}

/** Stack arranges children; direction is "horizontal" or "vertical". */
export function Stack(direction: string, gap: number, ...els: Elish[]): Element {
  return compose("Stack", { direction, gap }, els);
}

/** Hero is a featured banner. Fill its call-to-action row with Actions. */
export function Hero(title: string, ...els: Elish[]): Element {
  return compose("HeroBanner", { title }, els);
}

/** PosterCard renders a work/item card. */
export function PosterCard(title: string, mediaType: string, ...els: Elish[]): Element {
  return compose("PosterCard", { title, mediaType }, els);
}

/** Button carries an action; variant is primary/secondary/ghost/danger. */
export function Button(label: string, variant: string, ...els: Elish[]): Element {
  return compose("Button", { label, variant }, els);
}

/** Badge is a small pill; tone is one of the Tone values. */
export function Badge(label: string, tone: string, ...els: Elish[]): Element {
  return compose("Badge", { label, tone }, els);
}

/** Banner is an inline message; tone is one of the Tone values. */
export function Banner(message: string, tone: string, ...els: Elish[]): Element {
  return compose("Banner", { message, tone }, els);
}

/** DetailHeader renders a node's metadata (title, meta, genres). */
export function DetailHeader(title: string, ...els: Elish[]): Element {
  return compose("DetailHeader", { title }, els);
}

/** EpisodeRow renders one episode under a season. */
export function EpisodeRow(title: string, ...els: Elish[]): Element {
  return compose("EpisodeRow", { title }, els);
}

/** PersonChip is a cast/crew chip. */
export function PersonChip(name: string, ...els: Elish[]): Element {
  return compose("PersonChip", { name }, els);
}

/** GenreTag is a genre chip. */
export function GenreTag(label: string, ...els: Elish[]): Element {
  return compose("GenreTag", { label }, els);
}

/** Player renders a video surface over a server-issued playback ticket (ADR 0047). The client owns the decoding pipeline and the transport controls; every field here is server-decided. */
export function Player(src: string, ...els: Elish[]): Element {
  return compose("Player", { src }, els);
}

/** EmptyState is a titled empty placeholder. */
export function EmptyState(icon: string, title: string): Element {
  return compose("EmptyState", { icon, title }, []);
}

/** Component is the generic constructor for a type without a helper (a standard component like SeasonSelector, or a module's own). */
export function Component(typ: string, ...els: Elish[]): Element {
  return compose(typ, undefined, els);
}

// ── slots ──────────────────────────────────────────────────────────────────

/** Actions fills the "actions" slot (a hero's CTA row). */
export function Actions(...els: Elish[]): El {
  return Slot("actions", ...els);
}

/** Aside fills the "aside" slot (a hero's docked poster). */
export function Aside(...els: Elish[]): El {
  return Slot("aside", ...els);
}

// ── sugar ──────────────────────────────────────────────────────────────────

/** OnTap sets the node's primary action. */
export function OnTap(v: Action): El {
  return Prop("action", v);
}

/** Title sets a screen or component title. */
export function Title(v: string): El {
  return Prop("title", v);
}

/** Subtitle sets a card/row subtitle. */
export function Subtitle(v: string): El {
  return Prop("subtitle", v);
}

/** Poster sets a poster image URL. */
export function Poster(v: string): El {
  return Prop("poster", v);
}

/** Backdrop sets a hero backdrop image URL. */
export function Backdrop(v: string): El {
  return Prop("backdrop", v);
}

/** Logo sets a hero clearlogo/title-treatment image URL. */
export function Logo(v: string): El {
  return Prop("logo", v);
}

/** Overview sets a synopsis/overview string. */
export function Overview(v: string): El {
  return Prop("overview", v);
}

/** Progress sets a 0..1 watched fraction. */
export function Progress(v: number): El {
  return Prop("progress", v);
}

/** BadgeText sets a corner badge on a card. */
export function BadgeText(v: string): El {
  return Prop("badge", v);
}

/** ActionLabel sets a Section's "see all" action label (paired with OnTap). */
export function ActionLabel(v: string): El {
  return Prop("actionLabel", v);
}

/** Meta sets a hero's meta line (year, type, rating). */
export function Meta(...v: string[]): El {
  return Prop("meta", v);
}

/** Genres sets a DetailHeader's genre list. */
export function Genres(...v: string[]): El {
  return Prop("genres", v);
}

/** ResumeAt sets the position in seconds a Player starts from (ADR 0046). */
export function ResumeAt(v: number): El {
  return Prop("resumeAt", v);
}

/** MimeType sets the media type a Player should expect, so a client can pick a pipeline before it fetches. */
export function MimeType(v: string): El {
  return Prop("mimeType", v);
}

// Tone values (the open-bag string encoding), mirroring the Go Tone constants.
export const ToneNeutral = "neutral" as const;
export const ToneSuccess = "success" as const;
export const ToneWarning = "warning" as const;
export const ToneDanger = "danger" as const;
export const ToneInfo = "info" as const;

// ── actions ────────────────────────────────────────────────────────────────
// Actions ride inside the open props bag as JSON (ADR 0044); each constructor
// hides the discriminator and the optional fields.

/** Navigate pushes a screen, optionally with params. */
export function Navigate(screen: string, params?: Props): Action {
  return { kind: ActionKind.Navigate, screen, ...(params ? { params } : {}) };
}

/** Invoke runs a server mutation, optionally with input. */
export function Invoke(mutation: string, input?: Props): Action {
  return { kind: ActionKind.Invoke, mutation, ...(input ? { input } : {}) };
}

/** Play starts playback of a part. */
export function Play(partId: string): Action {
  return { kind: ActionKind.PlayPart, partId };
}

/** OpenURL opens an external URL (the client validates the scheme). */
export function OpenURL(url: string): Action {
  return { kind: ActionKind.OpenURL, url };
}
