// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 the Mosaic authors

// Package mosaic.session.v1 is the first-party client session transport
// (ADR 0041): a typed, two-lane RPC surface generated from this one .proto into
// every client language. It supersedes the bespoke WebSocket of ADR 0032 and
// folds ADR 0033's live handover into stream resume.
//
// Two lanes, mapping onto the two gRPC shapes supported uniformly on every
// target client (web via Connect, Flutter, Compose, Swift):
//
//   - Lane 1 — intents (unary). Navigate, Invoke, SubmitInput, Attach. Each
//     resolves to the same application command/query the HTTP path would; the
//     command boundary (ADR 0016) and caller model (ADR 0017) are unchanged.
//   - Lane 2 — push (server-streaming). One long-lived Subscribe stream per
//     session over which the server pushes region updates, shell mutations,
//     toasts and unsolicited events. resume_cursor replays what a reconnecting
//     client missed.
//
// Deliberately no bidirectional streaming: unary + server-streaming are the one
// pair browsers support, so the wire stays uniform across all four clients.
//
// UINode subtrees ride the envelope as the typed mosaic.sdui.v1.UINode — ADR
// 0044 (option (b) of ADR 0041): the SDUI contract is protobuf, so the whole
// wire is typed end to end. Open bags that are genuinely screen- or
// action-specific (params, input, event payloads) still ride as JSON bytes.

// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=none"
// @generated from file mosaic/session/v1/session.proto (package mosaic.session.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { UINode } from "../../sdui/v1/sdui_pb";
import { file_mosaic_sdui_v1_sdui } from "../../sdui/v1/sdui_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mosaic/session/v1/session.proto.
 */
export const file_mosaic_session_v1_session: GenFile = /*@__PURE__*/
  fileDesc("Ch9tb3NhaWMvc2Vzc2lvbi92MS9zZXNzaW9uLnByb3RvEhFtb3NhaWMuc2Vzc2lvbi52MSIFCgNBY2siQAoNQXR0YWNoUmVxdWVzdBIPCgdzZXNzaW9uGAEgASgJEg4KBnNjcmVlbhgCIAEoCRIOCgZwYXJhbXMYAyABKAwiQgoPTmF2aWdhdGVSZXF1ZXN0Eg8KB3Nlc3Npb24YASABKAkSDgoGc2NyZWVuGAIgASgJEg4KBnBhcmFtcxgDIAEoDCI/Cg1JbnZva2VSZXF1ZXN0Eg8KB3Nlc3Npb24YASABKAkSDgoGYWN0aW9uGAIgASgJEg0KBWlucHV0GAMgASgMIi4KDElucHV0UmVxdWVzdBIPCgdzZXNzaW9uGAEgASgJEg0KBXZhbHVlGAIgASgJIjoKEFN1YnNjcmliZVJlcXVlc3QSDwoHc2Vzc2lvbhgBIAEoCRIVCg1yZXN1bWVfY3Vyc29yGAIgASgEIt4BCg1TZXJ2ZXJNZXNzYWdlEgsKA3NlcRgBIAEoBBIxCgZyZWdpb24YAiABKAsyHy5tb3NhaWMuc2Vzc2lvbi52MS5SZWdpb25VcGRhdGVIABIvCgVzaGVsbBgDIAEoCzIeLm1vc2FpYy5zZXNzaW9uLnYxLlNoZWxsVXBkYXRlSAASKQoFdG9hc3QYBCABKAsyGC5tb3NhaWMuc2Vzc2lvbi52MS5Ub2FzdEgAEikKBWV2ZW50GAUgASgLMhgubW9zYWljLnNlc3Npb24udjEuRXZlbnRIAEIGCgRib2R5IroBCgxSZWdpb25VcGRhdGUSDgoGcmVnaW9uGAEgASgJEi4KAm9wGAIgASgOMiIubW9zYWljLnNlc3Npb24udjEuUmVnaW9uVXBkYXRlLk9wEicKB3VpX25vZGUYAyABKAsyFi5tb3NhaWMuc2R1aS52MS5VSU5vZGUiQQoCT3ASCwoHUkVQTEFDRRAAEgoKBkFQUEVORBABEgsKB1BSRVBFTkQQAhIKCgZSRU1PVkUQAxIJCgVQQVRDSBAEIjYKC1NoZWxsVXBkYXRlEicKB3VpX25vZGUYASABKAsyFi5tb3NhaWMuc2R1aS52MS5VSU5vZGUiJgoFVG9hc3QSDwoHbWVzc2FnZRgBIAEoCRIMCgR0b25lGAIgASgJIiYKBUV2ZW50EgwKBHR5cGUYASABKAkSDwoHcGF5bG9hZBgCIAEoDDL+AgoOU2Vzc2lvblNlcnZpY2USQgoGQXR0YWNoEiAubW9zYWljLnNlc3Npb24udjEuQXR0YWNoUmVxdWVzdBoWLm1vc2FpYy5zZXNzaW9uLnYxLkFjaxJGCghOYXZpZ2F0ZRIiLm1vc2FpYy5zZXNzaW9uLnYxLk5hdmlnYXRlUmVxdWVzdBoWLm1vc2FpYy5zZXNzaW9uLnYxLkFjaxJCCgZJbnZva2USIC5tb3NhaWMuc2Vzc2lvbi52MS5JbnZva2VSZXF1ZXN0GhYubW9zYWljLnNlc3Npb24udjEuQWNrEkYKC1N1Ym1pdElucHV0Eh8ubW9zYWljLnNlc3Npb24udjEuSW5wdXRSZXF1ZXN0GhYubW9zYWljLnNlc3Npb24udjEuQWNrElQKCVN1YnNjcmliZRIjLm1vc2FpYy5zZXNzaW9uLnYxLlN1YnNjcmliZVJlcXVlc3QaIC5tb3NhaWMuc2Vzc2lvbi52MS5TZXJ2ZXJNZXNzYWdlMAFCPlo8Z2l0aHViLmNvbS9tb3NhaWMtbWVkaWEvc2R1aS9nZW4vbW9zYWljL3Nlc3Npb24vdjE7c2Vzc2lvbnYxYgZwcm90bzM", [file_mosaic_sdui_v1_sdui]);

/**
 * Ack is the empty reply to an intent. An intent either succeeds (Ack) or fails
 * with a Connect/gRPC error carrying a Platform error category; its visible
 * effect arrives on the push lane, not in this reply.
 *
 * @generated from message mosaic.session.v1.Ack
 */
export type Ack = Message<"mosaic.session.v1.Ack"> & {
};

/**
 * Describes the message mosaic.session.v1.Ack.
 * Use `create(AckSchema)` to create a new message.
 */
export const AckSchema: GenMessage<Ack> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 0);

/**
 * AttachRequest binds a session and optionally declares the route to show.
 *
 * @generated from message mosaic.session.v1.AttachRequest
 */
export type AttachRequest = Message<"mosaic.session.v1.AttachRequest"> & {
  /**
   * opaque session ref (ADR 0017); auth is on this call.
   *
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * optional route to (re-)assert; empty leaves it unchanged.
   *
   * @generated from field: string screen = 2;
   */
  screen: string;

  /**
   * optional screen params as a JSON object (see params note).
   *
   * @generated from field: bytes params = 3;
   */
  params: Uint8Array;
};

/**
 * Describes the message mosaic.session.v1.AttachRequest.
 * Use `create(AttachRequestSchema)` to create a new message.
 */
export const AttachRequestSchema: GenMessage<AttachRequest> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 1);

/**
 * NavigateRequest opens a screen.
 *
 * @generated from message mosaic.session.v1.NavigateRequest
 */
export type NavigateRequest = Message<"mosaic.session.v1.NavigateRequest"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * @generated from field: string screen = 2;
   */
  screen: string;

  /**
   * screen params as a JSON object (see params note).
   *
   * @generated from field: bytes params = 3;
   */
  params: Uint8Array;
};

/**
 * Describes the message mosaic.session.v1.NavigateRequest.
 * Use `create(NavigateRequestSchema)` to create a new message.
 */
export const NavigateRequestSchema: GenMessage<NavigateRequest> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 2);

/**
 * InvokeRequest runs a named action. input is the action's argument envelope in
 * the SDUI runtime's JSON shape (ADR 0029), carried opaquely and decoded by the
 * action's Platform handler.
 *
 * @generated from message mosaic.session.v1.InvokeRequest
 */
export type InvokeRequest = Message<"mosaic.session.v1.InvokeRequest"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * the action/mutation name, e.g. "importContent".
   *
   * @generated from field: string action = 2;
   */
  action: string;

  /**
   * JSON argument envelope.
   *
   * @generated from field: bytes input = 3;
   */
  input: Uint8Array;
};

/**
 * Describes the message mosaic.session.v1.InvokeRequest.
 * Use `create(InvokeRequestSchema)` to create a new message.
 */
export const InvokeRequestSchema: GenMessage<InvokeRequest> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 3);

/**
 * InputRequest carries one search-as-you-type value.
 *
 * @generated from message mosaic.session.v1.InputRequest
 */
export type InputRequest = Message<"mosaic.session.v1.InputRequest"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message mosaic.session.v1.InputRequest.
 * Use `create(InputRequestSchema)` to create a new message.
 */
export const InputRequestSchema: GenMessage<InputRequest> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 4);

/**
 * SubscribeRequest opens the push lane. resume_cursor is the last
 * ServerMessage.seq the client saw; 0 on a fresh connect.
 *
 * @generated from message mosaic.session.v1.SubscribeRequest
 */
export type SubscribeRequest = Message<"mosaic.session.v1.SubscribeRequest"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * @generated from field: uint64 resume_cursor = 2;
   */
  resumeCursor: bigint;
};

/**
 * Describes the message mosaic.session.v1.SubscribeRequest.
 * Use `create(SubscribeRequestSchema)` to create a new message.
 */
export const SubscribeRequestSchema: GenMessage<SubscribeRequest> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 5);

/**
 * ServerMessage is one push. seq is monotonic per session and is the resume
 * cursor a reconnecting client presents.
 *
 * A note on params/input as JSON bytes: screen params and action inputs are an
 * open, screen- and action-specific bag (a content ref, a season number, a
 * search string), so they ride as a JSON object rather than a fixed message —
 * the typed envelope carries an open payload where the payload is genuinely
 * open, while the UI tree itself is the typed mosaic.sdui.v1.UINode.
 *
 * @generated from message mosaic.session.v1.ServerMessage
 */
export type ServerMessage = Message<"mosaic.session.v1.ServerMessage"> & {
  /**
   * @generated from field: uint64 seq = 1;
   */
  seq: bigint;

  /**
   * @generated from oneof mosaic.session.v1.ServerMessage.body
   */
  body: {
    /**
     * a named region changed.
     *
     * @generated from field: mosaic.session.v1.RegionUpdate region = 2;
     */
    value: RegionUpdate;
    case: "region";
  } | {
    /**
     * the app shell (re)rendered.
     *
     * @generated from field: mosaic.session.v1.ShellUpdate shell = 3;
     */
    value: ShellUpdate;
    case: "shell";
  } | {
    /**
     * a transient notice.
     *
     * @generated from field: mosaic.session.v1.Toast toast = 4;
     */
    value: Toast;
    case: "toast";
  } | {
    /**
     * an unsolicited domain event.
     *
     * @generated from field: mosaic.session.v1.Event event = 5;
     */
    value: Event;
    case: "event";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message mosaic.session.v1.ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export const ServerMessageSchema: GenMessage<ServerMessage> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 6);

/**
 * RegionUpdate applies one operation to a named region (ADR 0029 / 0031). The
 * op-set is contract-owned and transport-agnostic: a Compose composable, a
 * SwiftUI view and a React component apply the same ops.
 *
 * @generated from message mosaic.session.v1.RegionUpdate
 */
export type RegionUpdate = Message<"mosaic.session.v1.RegionUpdate"> & {
  /**
   * a named slot (ADR 0029 / 0031), e.g. "content".
   *
   * @generated from field: string region = 1;
   */
  region: string;

  /**
   * @generated from field: mosaic.session.v1.RegionUpdate.Op op = 2;
   */
  op: RegionUpdate_Op;

  /**
   * the typed UINode subtree (ADR 0044).
   *
   * @generated from field: mosaic.sdui.v1.UINode ui_node = 3;
   */
  uiNode?: UINode | undefined;
};

/**
 * Describes the message mosaic.session.v1.RegionUpdate.
 * Use `create(RegionUpdateSchema)` to create a new message.
 */
export const RegionUpdateSchema: GenMessage<RegionUpdate> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 7);

/**
 * Op is the region operation. REPLACE is the whole-region default; the
 * narrower ops let a producer target part of a region without resending it.
 *
 * @generated from enum mosaic.session.v1.RegionUpdate.Op
 */
export enum RegionUpdate_Op {
  /**
   * @generated from enum value: REPLACE = 0;
   */
  REPLACE = 0,

  /**
   * @generated from enum value: APPEND = 1;
   */
  APPEND = 1,

  /**
   * @generated from enum value: PREPEND = 2;
   */
  PREPEND = 2,

  /**
   * @generated from enum value: REMOVE = 3;
   */
  REMOVE = 3,

  /**
   * @generated from enum value: PATCH = 4;
   */
  PATCH = 4,
}

/**
 * Describes the enum mosaic.session.v1.RegionUpdate.Op.
 */
export const RegionUpdate_OpSchema: GenEnum<RegionUpdate_Op> = /*@__PURE__*/
  enumDesc(file_mosaic_session_v1_session, 7, 0);

/**
 * ShellUpdate carries the app shell UINode tree (ADR 0031). It is sent once on
 * connect and again only if the shell itself changes.
 *
 * @generated from message mosaic.session.v1.ShellUpdate
 */
export type ShellUpdate = Message<"mosaic.session.v1.ShellUpdate"> & {
  /**
   * the typed shell UINode tree (ADR 0044).
   *
   * @generated from field: mosaic.sdui.v1.UINode ui_node = 1;
   */
  uiNode?: UINode | undefined;
};

/**
 * Describes the message mosaic.session.v1.ShellUpdate.
 * Use `create(ShellUpdateSchema)` to create a new message.
 */
export const ShellUpdateSchema: GenMessage<ShellUpdate> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 8);

/**
 * Toast is a transient notice — the confirmation an Invoke pushes.
 *
 * @generated from message mosaic.session.v1.Toast
 */
export type Toast = Message<"mosaic.session.v1.Toast"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * "success" | "danger" | "info" — an SDUI tone.
   *
   * @generated from field: string tone = 2;
   */
  tone: string;
};

/**
 * Describes the message mosaic.session.v1.Toast.
 * Use `create(ToastSchema)` to create a new message.
 */
export const ToastSchema: GenMessage<Toast> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 9);

/**
 * Event is an unsolicited domain event: an import finished, a config changed, a
 * library edit from another device. This is the channel request/response cannot
 * provide and the reason a live lane exists at all.
 *
 * @generated from message mosaic.session.v1.Event
 */
export type Event = Message<"mosaic.session.v1.Event"> & {
  /**
   * event type name.
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * event-specific JSON payload.
   *
   * @generated from field: bytes payload = 2;
   */
  payload: Uint8Array;
};

/**
 * Describes the message mosaic.session.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 10);

/**
 * SessionService is the live client session. Intents are unary; push is one
 * server-streaming call. Over HTTP/2 both lanes multiplex onto a single
 * connection, so the two-lane logical split costs one physical connection.
 *
 * @generated from service mosaic.session.v1.SessionService
 */
export const SessionService: GenService<{
  /**
   * Attach (re)binds this caller to a session and declares the route it wants
   * shown. A reconnecting client calls it to re-assert the exact screen that
   * was open, the same re-declaration the ADR 0032 socket did on reconnect.
   *
   * @generated from rpc mosaic.session.v1.SessionService.Attach
   */
  attach: {
    methodKind: "unary";
    input: typeof AttachRequestSchema;
    output: typeof AckSchema;
  },
  /**
   * Navigate opens a screen; the server renders it into the content region on
   * the push lane.
   *
   * @generated from rpc mosaic.session.v1.SessionService.Navigate
   */
  navigate: {
    methodKind: "unary";
    input: typeof NavigateRequestSchema;
    output: typeof AckSchema;
  },
  /**
   * Invoke runs a named action (an SDUI Action, ADR 0029) — a mutation — and
   * pushes a toast plus a re-render of the current content.
   *
   * @generated from rpc mosaic.session.v1.SessionService.Invoke
   */
  invoke: {
    methodKind: "unary";
    input: typeof InvokeRequestSchema;
    output: typeof AckSchema;
  },
  /**
   * SubmitInput carries one search-as-you-type keystroke. The Platform
   * debounces these against session state before sourcing, so a fast typist
   * does not fan out a request per keystroke to the upstream addons.
   *
   * @generated from rpc mosaic.session.v1.SessionService.SubmitInput
   */
  submitInput: {
    methodKind: "unary";
    input: typeof InputRequestSchema;
    output: typeof AckSchema;
  },
  /**
   * Subscribe opens the push lane: one long-lived server-stream per session.
   * resume_cursor replays what a reconnecting client missed (superseding ADR
   * 0033's handover).
   *
   * @generated from rpc mosaic.session.v1.SessionService.Subscribe
   */
  subscribe: {
    methodKind: "server_streaming";
    input: typeof SubscribeRequestSchema;
    output: typeof ServerMessageSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_mosaic_session_v1_session, 0);

