// Code generated by tools/genui from ui.spec.json. DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 the Mosaic authors

package ui

import "github.com/mosaic-media/sdui/sdui"

// ── components ─────────────────────────────────────────────────────────────

// Screen is the root of a server-defined page.
func Screen(els ...El) *Element { return compose("Screen", nil, els) }

// Section is a titled band.
func Section(title string, els ...El) *Element {
	return compose("Section", map[string]any{"title": title}, els)
}

// Carousel is a horizontal snap-scrolling rail.
func Carousel(els ...El) *Element { return compose("Carousel", nil, els) }

// Grid is a responsive auto-fill grid.
func Grid(els ...El) *Element { return compose("Grid", nil, els) }

// Stack arranges children; direction is "horizontal" or "vertical".
func Stack(direction string, gap int, els ...El) *Element {
	return compose("Stack", map[string]any{"direction": direction, "gap": gap}, els)
}

// Hero is a featured banner. Fill its call-to-action row with Actions.
func Hero(title string, els ...El) *Element {
	return compose("HeroBanner", map[string]any{"title": title}, els)
}

// PosterCard renders a work/item card.
func PosterCard(title string, mediaType string, els ...El) *Element {
	return compose("PosterCard", map[string]any{"title": title, "mediaType": mediaType}, els)
}

// Button carries an action; variant is primary/secondary/ghost/danger.
func Button(label string, variant string, els ...El) *Element {
	return compose("Button", map[string]any{"label": label, "variant": variant}, els)
}

// Badge is a small pill; tone is one of the Tone values.
func Badge(label string, tone string, els ...El) *Element {
	return compose("Badge", map[string]any{"label": label, "tone": tone}, els)
}

// Banner is an inline message; tone is one of the Tone values.
func Banner(message string, tone string, els ...El) *Element {
	return compose("Banner", map[string]any{"message": message, "tone": tone}, els)
}

// DetailHeader renders a node's metadata (title, meta, genres).
func DetailHeader(title string, els ...El) *Element {
	return compose("DetailHeader", map[string]any{"title": title}, els)
}

// EpisodeRow renders one episode under a season.
func EpisodeRow(title string, els ...El) *Element {
	return compose("EpisodeRow", map[string]any{"title": title}, els)
}

// PersonChip is a cast/crew chip.
func PersonChip(name string, els ...El) *Element {
	return compose("PersonChip", map[string]any{"name": name}, els)
}

// GenreTag is a genre chip.
func GenreTag(label string, els ...El) *Element {
	return compose("GenreTag", map[string]any{"label": label}, els)
}

// Player renders a video surface over a server-issued playback ticket (ADR 0047). The client owns the decoding pipeline and the transport controls; every field here is server-decided.
func Player(src string, els ...El) *Element {
	return compose("Player", map[string]any{"src": src}, els)
}

// EmptyState is a titled empty placeholder.
func EmptyState(icon string, title string) *Element {
	return compose("EmptyState", map[string]any{"icon": icon, "title": title}, nil)
}

// Component is the generic constructor for a type without a helper (a standard component like SeasonSelector, or a module's own).
func Component(typ string, els ...El) *Element { return compose(typ, nil, els) }

// ── slots ──────────────────────────────────────────────────────────────────

// Actions fills the "actions" slot (a hero's CTA row).
func Actions(els ...El) El { return Slot("actions", els...) }

// Aside fills the "aside" slot (a hero's docked poster).
func Aside(els ...El) El { return Slot("aside", els...) }

// ── sugar ──────────────────────────────────────────────────────────────────

// OnTap sets the node's primary action.
func OnTap(v Action) El { return Prop("action", v) }

// Title sets a screen or component title.
func Title(v string) El { return Prop("title", v) }

// Subtitle sets a card/row subtitle.
func Subtitle(v string) El { return Prop("subtitle", v) }

// Poster sets a poster image URL.
func Poster(v string) El { return Prop("poster", v) }

// Backdrop sets a hero backdrop image URL.
func Backdrop(v string) El { return Prop("backdrop", v) }

// Logo sets a hero clearlogo/title-treatment image URL.
func Logo(v string) El { return Prop("logo", v) }

// Overview sets a synopsis/overview string.
func Overview(v string) El { return Prop("overview", v) }

// Progress sets a 0..1 watched fraction.
func Progress(v float64) El { return Prop("progress", v) }

// BadgeText sets a corner badge on a card.
func BadgeText(v string) El { return Prop("badge", v) }

// ActionLabel sets a Section's "see all" action label (paired with OnTap).
func ActionLabel(v string) El { return Prop("actionLabel", v) }

// Meta sets a hero's meta line (year, type, rating).
func Meta(v ...string) El { return Prop("meta", v) }

// Genres sets a DetailHeader's genre list.
func Genres(v ...string) El { return Prop("genres", v) }

// ResumeAt sets the position in seconds a Player starts from (ADR 0046).
func ResumeAt(v float64) El { return Prop("resumeAt", v) }

// MimeType sets the media type a Player should expect, so a client can pick a pipeline before it fetches.
func MimeType(v string) El { return Prop("mimeType", v) }

// Tone values (the open-bag string encoding), re-exported from the producer binding.
const (
	ToneNeutral = sdui.ToneNeutral
	ToneSuccess = sdui.ToneSuccess
	ToneWarning = sdui.ToneWarning
	ToneDanger  = sdui.ToneDanger
	ToneInfo    = sdui.ToneInfo
)

// Action constructors, re-exported from the producer binding; they ride the open
// props bag as JSON (ADR 0044).
var (
	Navigate = sdui.Navigate
	Invoke   = sdui.Invoke
	Play     = sdui.Play
	OpenURL  = sdui.OpenURL
)
